### ISSUE TITLE
Category list has white text for each item in table

### ISSUE THREAD

**Issue by chriswaterside** [ramblerswebs/Gantry5_Template#12]
Keith
when you have a menu item that displays a Category list it seems to have white text for each item in table.
see https://j4test.ramblers-webs.org.uk/about-us.html
on inspection it seems that each line in the table is a TH tag rather than TD and this is causing the issue. So I guess the template is doing that.
Chris

**Comment by keithgrimes** [comment]
Chris, this is not an issue with the template but a bug within Joomla 4. J4 writes the structure of the table, the template only structures it into the correct position on the page. 

I have raised an issue ticket within the Joomla4 Github area, but also include a fix in the next template to overcome this and set the colour to the main text colour.
