### ISSUE TITLE
Test.derbyramblers.org.uk lost header

### ISSUE THREAD

**Issue by ramblerswebs** [ramblerswebs/Gantry5_Template#4]
With the update the header module seems to have got lost

**Comment by keithgrimes** [comment]
Chris, this was not down to the template. The header was set only to display for members (registered users) and should be set to public. don't know if this is down to the fact you have 2 header modules but I have disabled the other. The header now displays correctly. 

Regards

Keith.

**Comment by ramblerswebs** [comment]
Keith
the headers are one for guests and one for members who have logged on.
Not sure how but the guest one was in a toolbar position, so changed it to top-a and now works fine
Sorry I should have spotted this.
