### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by ramblerswebs** [ramblerswebs/Gantry5_Template#6]
I see there are two style / colour schemes
Can the others that Gantry 4 supports be added?

**Comment by keithgrimes** [comment]
We have have more styles/schemes but they only cover certain settings (those on the style page). Can you let me know where the Gantry4 ones are defined and I will look to include.

**Comment by ramblerswebs** [comment]
You can either go into the Gantry 4 template on test. and look in Style
or at https://www.ramblers-webs.org.uk/joomla3/2022-branding.html and search for **List of menu styling options**

**Comment by keithgrimes** [comment]
These have now been added in version 1.0.18 of the template.
